### ISSUE TITLE
Configuring llvm  ERROR

### ISSUE THREAD

**Issue by liutianshx2012** [macmade/XEOS#3]
The LLVM project no longer supports building with configure & make.

**Comment by macmade** [comment]
Issue has been fixed in master.  
LLVM is now build through CMake.

Also CMake has been updated to version 3.7.1, so be sure to rebuild the complete toolchain before proceeding with LLVM...

**Comment by liutianshx2012** [comment]
how to run  it ~

**Comment by macmade** [comment]
@liutianshx2012  I would have helped you, but looking at your repositories, I'm really concerned about your behaviour on OpenSource projects, as it appears you are just **stealing code for your own OS project**.

As an example:  
https://github.com/liutianshx2012/TClib/blob/master/dictionary.h and https://github.com/liutianshx2012/TClib/blob/master/dictionary.c

**This code actually comes from my repository: https://github.com/macmade/Dictionary**.

What's wrong with you?  
**It's not because you reformat the code to suit your own coding conventions that you can get rid of the original copyright/license and claim you wrote it by adding your own copyright!**  
This is not how it works!

Same here: https://github.com/liutianshx2012/TOS-makefile  
This is my code, from https://github.com/macmade/XEOS-makefile, but with your own copyright.  
**Again, you can use that makefile if you need to, but you can't remove the original copyright statement.  
Even if you modify the file, you still have to retain the copyright statements.**

Same on https://github.com/liutianshx2012/TOS-lib-c99/tree/master/include/c99.  
This is just a copy/paste from XEOS's C99 headers (https://github.com/macmade/XEOS-lib-c99), without attribution.  
**Even if you plan to write the implementation by yourself, if you use my own headers, you'll have to keep the original copyright!**

You even forgot to replace the "XEOS" mention on a README file: https://github.com/liutianshx2012/Tlibposix

I'll stop here...

**So for now I'll politely ask you to fix these issues as soon as possible.**

I'm using permissive licences, you're free to use and modify my code, assuming you respect the license terms.  
**You cannot steal code from others, remove their copyrights, and claim you did the work!**

I also noticed that the structure of your OS project just mimics the structure of XEOS, with the same sub-repositories, with the exact same names.  
While it's OK to do this, **I encourage you to do your own stuff**.

**An OS project is exciting, but you'll learn much more by learning and doing stuff by yourself, rather than trying to copy what other people are doing.**  
Do not try to go too fast. Try experimenting with your own code and own structure... 

Regards,

**Comment by liutianshx2012** [comment]
i just want to learn it , so sorry~
